### YamlMime:ManagedReference
items:
- uid: Pagene.BlogSettings
  commentId: N:Pagene.BlogSettings
  id: Pagene.BlogSettings
  children:
  - Pagene.BlogSettings.AppConfigLoader
  - Pagene.BlogSettings.AppPathInfo
  - Pagene.BlogSettings.ConvertingInfo
  - Pagene.BlogSettings.RoutePathInfo
  langs:
  - csharp
  - vb
  name: Pagene.BlogSettings
  nameWithType: Pagene.BlogSettings
  fullName: Pagene.BlogSettings
  type: Namespace
  assemblies:
  - Pagene.BlogSettings
references:
- uid: Pagene.BlogSettings.AppConfigLoader
  commentId: T:Pagene.BlogSettings.AppConfigLoader
  name: AppConfigLoader
  nameWithType: AppConfigLoader
  fullName: Pagene.BlogSettings.AppConfigLoader
- uid: Pagene.BlogSettings.AppPathInfo
  commentId: T:Pagene.BlogSettings.AppPathInfo
  name: AppPathInfo
  nameWithType: AppPathInfo
  fullName: Pagene.BlogSettings.AppPathInfo
- uid: Pagene.BlogSettings.ConvertingInfo
  commentId: T:Pagene.BlogSettings.ConvertingInfo
  name: ConvertingInfo
  nameWithType: ConvertingInfo
  fullName: Pagene.BlogSettings.ConvertingInfo
- uid: Pagene.BlogSettings.RoutePathInfo
  commentId: T:Pagene.BlogSettings.RoutePathInfo
  name: RoutePathInfo
  nameWithType: RoutePathInfo
  fullName: Pagene.BlogSettings.RoutePathInfo
